sudo: false
language: python
cache:
    - pip
    - directories:
        - usr
        - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/
        - /home/travis/virtualenv/python2.7.9/bin/
python:
  - "2.7"
before_install:
  - source .travis_ssh_setup.sh
  - source .travis_install.sh
install:
  - pip install matplotlib pygments pyparsing ply zodb numpy
  - pip install git+https://github.com/zardus/z3.git@py-setup
  - pip install git+https://github.com/bdcht/grandalf
  - pip install git+https://github.com/bdcht/crysp
  - pip install git+https://github.com/bdcht/amoco
  - pip install -e .
  - pip install -r docs/requirements.txt
before_script:
  - python -c 'from pwn import *; print pwnlib.term.term_mode' NOTERM
  - python -c 'from pwn import *; print pwnlib.term.term_mode' NOTERM
  - python -c 'from pwn import *; print pwnlib.term.term_mode' NOTERM
  - python -c 'from pwn import *; print pwnlib.term.term_mode' NOTERM
script: PWNLIB_NOTERM=1 make -C docs doctest

